State <|-- WashingState
State <|-- IdleState
WashingState <|-- CottonState
WashingState <|-- DisinfectionState
WashingState <|-- RoughState
WashingState <|-- SoakingSpinningState
WashingState <|-- SyntheticState

class State {
    name : String
    isDoorOpened : Boolean
}

class WashingState {
    waterTemperature : Celcius
    waterLevel : Percentage
    washingDuration : Minute
    washingSpeed : AgitationPerMinute
    washingUseSoap : Boolean
    washingUseBleach : Boolean
    washingUseFabricSoftener : Boolean
    spinningDuration : Minute
    spinningSpeed : RotationPerMinute
}

class IdleState {
}

class CottonState {
}

class DisinfectionState {
}

class RoughState {
}

class SoakingSpinningState {
}

class SyntheticState {
}
